name: Publish docs

on:
  push:
    branches: [documentation]
  pull_request:
    branches: [documentation]
  workflow_dispatch:

jobs:
  build:
    uses: Conduction/.github/.forgejo/workflows/documentation-build.yml@main
    with:
      source-folder: docs
    secrets: inherit

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    uses: Conduction/.github/.forgejo/workflows/documentation-deploy.yml@main
    with:
      cf-project-name: hermiq-docs
    secrets: inherit
